### PR TITLE
Setup the GitHub Action

### PR DESCRIPTION
**Pull request by AlbertLee125**
Used the workflows to find whether the Jekyll workflow works.
I hope this act make the jupyter book to be fixing the pages.

### CODE REVIEW

**Comment by ZedongPeng** [comment]
I don't think this `yml` file works. It should work for `Jekyll` not for `JupyterBook`.
Why don't you use the one in the JupyterBook documentation?
https://jupyterbook.org/en/stable/publish/gh-pages.html

**Comment by AlbertLee125** [comment]
Did you mean copy and paste?

**Comment by ZedongPeng** [comment]
No one knows if it works before testing. Have you tested it?
https://stackoverflow.com/questions/67707244/how-to-test-github-workflow-without-merging-into-master-main-branch

**Comment by ZedongPeng** [comment]
We should never manually change the `html` files, which should be automatically generated.
Moreover, by setting up the GitHub action, we should be able to remove the whole `_build` folder.
You can refer to this repo: https://github.com/mobook/MO-book/tree/main?tab=readme-ov-file .

**Review by ZedongPeng — APPROVED** [review]

**Review by ZedongPeng — CHANGES_REQUESTED** [review]
Why do you add the `pyomo_summer_workshop` folder?

**Review by ZedongPeng — APPROVED** [review]

**Pull request merged**
